<a target="_blank" href="https://colab.research.google.com/github/LPolyakova/Linear_Algebra_for_CS_students/blob/main/CP/LA_05_Euclidean_spaces.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# ЛА-Комп'ютерний практикум-05. Евклідові простори

In [ ]:
# these imports may be useful

import pandas as pd
from scipy import linalg
from scipy.spatial.distance import pdist, cdist
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model


 #### Деякі інструменти, які стануть у нагоді

In [ ]:
# these tools may be useful

# inner product
e1 = np.array([1,2,2])
e2 = np.array([2,3,-4])
p = np.dot(e1, e2)
print(f'''Inner product of vectors e1={e1} and e2={e2} is {p}''')
print('___________________________________')

# calculate distance between points
metric = 'cosine'
d = cdist([e1], [e2], metric=metric) #array of pairwise distances, here of the shape (1,1)
print(f'''The {metric} distance between e1={e1} and e2={e2} is  {d[0][0]}''')
print('___________________________________')


# vector norm, matrix norm
A = np.array([[1,1], [0,1]])
e1_norm = np.linalg.norm(e1) # default Euclidean norm
A_norm = np.linalg.norm(A)   # default Frobenius norm
print(f'''Euclidean norm of e1={e1} is {e1_norm}. \n Frobenius norm of A={A} is {A_norm}''')
print('___________________________________')


# qr decomposition
B = np.array([[1, 2, 2, 0], [1, 1, -6, 1], [3, 2, 1, 1]]) #originally have three 4-vectors.
Bt = B.T  #write them as columns of a matrix
q, r = np.linalg.qr(Bt)
print(f'''QR-decomposition of {Bt} is Q={q}, R={r}. \n
It means that the columns of Q form the orthonormal basis of the space spanned by original vectors''')


Inner product of vectors e1=[1 2 2] and e2=[ 2  3 -4] is 0
___________________________________
The cosine distance between e1=[1 2 2] and e2=[ 2  3 -4] is  1.0
___________________________________
Euclidean norm of e1=[1 2 2] is 3.0. 
 Frobenius norm of A=[[1 1]
 [0 1]] is 1.7320508075688772
___________________________________
QR-decomposition of [[ 1  1  3]
 [ 2  1  2]
 [ 2 -6  1]
 [ 0  1  1]] is Q=[[-0.33333333 -0.36514837  0.77067464]
 [-0.66666667 -0.54772256 -0.49543369]
 [-0.66666667  0.73029674  0.11009638]
 [-0.         -0.18257419  0.38533732]], R=[[-3.          3.         -3.        ]
 [ 0.         -5.47722558 -1.64316767]
 [ 0.          0.          1.81659021]]. 

It means that the columns of Q form the orthonormal basis of the space spanned by original vectors


💻  **5.1. Ортонормований базис.** Напишіть функцію, яка перевіряє, чи є базис, що його дано на вході, ортонормованим. Напишіть функцію, яка розкладає даний вектор за  даним ортонормованим базисом, шукаючи його проекції на базисні вектори за допомогою скалярних добутків. Протестуйте свої функції. Для тестування можна використовувати дані з задач математичного практикуму.

In [ ]:
#write your code here

💻  **5.2. Алгоритм Грама-Шмідта.**  Напишіть програму, яка здійснює для даної системи векторів (довільної кількості) у $\mathbb{R}^4$ процес ортогоналізації та виводить ортонормований базис лінійної оболонки даних векторів. Порівняйте свої результати з QR-розкладом матриці, що складається з координат даних векторів. Для знаходження QR-розкладу можна використовувати numpy.linalg.qr або scipy.linalg.qr.

In [ ]:
#write your code here

💻  **5.3. Матриця проекції.** Напишіть функцію, яка обчислює матрицю ортогональної проекції на підпростір, натягнутий на дані вектори. Протестуйте цю функцію на прикладах (можна взяти приклади з математичного практикуму). Проілюструйте дію функції.

In [ ]:
#write your code here

💻  **5.4. Розв'язання трикутників.** Напишіть програму, яка за заданими трьома точками площини (або тривимірного простору)
1) Малює трикутник з вершинами у даних точках.
2) Обчислює довжини сторін трикутника.
3) Обчислює кути трикутника.

Використайте вбудовані функції, що обчислюють норми векторів та скалярні добутки. Також можна використати вбудовану функцію scipy.spatial.distance.pdist, що обчислює попарні відстані між точками й видає їх у вигляді списку або (якщо додатково застосувати функцію  squareform) у вигляді матриці.

In [ ]:
#write your code here

💻  **5.5. Ортогональна проекція і ортогональна складова.**

1️⃣Напишіть програму, які знаходять ортогональну проекцію і ортогональну складову даного вектора на даний підпростір. Вважайте, що підпростр задано як простір стопчиків деякої матриці. Розгляньте різні способи розв'язання ціє задачі: за допомогою матриці ортогональної проекції (що ви її знаходили у задачі 5.3); за допомогою розв'язання системи лінійних рівнянь (дивись приклади з математичного практикуму). Протестуйте ваші програми. Для векторів і підпросторів тривимірного простору зробіть ілюстрації.

In [ ]:
#write your code here

 2️⃣ Напишіть програму, яка знаходить відстань від заданої точки простору до заданого підпростору. Вважайте, що підпростр задано як простір стопчиків деякої матриці. Використайте ортогональну складову, що ви знаходили її в попередньому пункті.

In [ ]:
#write your code here

💻  **5.6. Що більше метрик, то краще.** Відстань між точками у просторі можна вимірювати не лише за допомогою евклідової метрики. Хоча лише евклідова метрика має природній вираз через скалярний добуток. Поекспериментуйте з різними метриками, що їх пропонує обчислювати модуль scipy.spatial.distance. Навчиться ними користуватися, зрозумійте їх геометричний зміст. Намалюйте в кожній з метрик одиничне коло, тобто множину точок, що знаходяться на відстані 1 від початку координат. Зверніть увагу на те, що ці "кола" не обов'язково круглі.

In [ ]:
#write your code here